# Tests for TP final

name: Tests for Ubuntu, Windows, and macOS

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: ${{ matrix.os }}  # Run on the OS defined below
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] 
        python: [3.11, 3.12]  # Different Python versions, for consistency

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: BACKEND - Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r back/requirements.txt

    - name: BACKEND - Run tests
      run: |
        cd back/Pokemon
        python pokemon_test.py

    - name: FRONTEND - Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.19' 

    - name: FRONTEND - Install dependencies
      run: |
        cd front
        npm install

    - name: FRONTEND - Start the application
      run: |
        cd front
        npm start &
      env:
        CI: true  # Necessary to prevent Create React App from prompting during npm start

    - name: FRONTEND - Run Cypress tests
      run: |
        cd front
        npx cypress run
      env:
        CYPRESS_baseUrl: http://localhost:3000  
